### ISSUE TITLE
height encoding in TimeSeries DSG

### ISSUE THREAD

**Issue by emiliom** [ioos/ioos-sos-issues-generic#3]
This is just a reference/link to the [ongoing discussion/issue on the i52n-sos repo](https://github.com/ioos/i52n-sos/issues/24), which has involved comparisons to the ncSOS implementations as well as pyoos client implementation. There's still some pyoos fixes and testing I intend to do later this month, plus a release with the i52N SOS fixes hasn't been done yet.

@abirger, if you don't think this belongs here, just go ahead and close it.

**Comment by srstsavage** [comment]
@emiliom Seems unnecessary to put this issue here since it only affects i52n-sos. The only references to ncSOS showed that ncSOS correctly encoded heights, so this isn't really a cross-implementation issue.

**Comment by abirger** [comment]
I think that @shane-axiom is right - this issue has a limited scope as it is just a bug in i52N. I am closing this issue here but it will still be available for reference as @emiliom wanted; the real issue tracking should be done in the [ioos/i52n-sos repo](https://github.com/ioos/i52n-sos/issues/24).
